import fs from 'node:fs/promises';
import path from 'node:path';
import { loadProject } from './config.js';

function psQuote(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}

export async function build(configFile) {
  const project = await loadProject(configFile);
  await fs.rm(project.outputDir, { recursive: true, force: true });
  await fs.mkdir(project.outputDir, { recursive: true });

  const packageInfo = {
    schemaVersion: 1,
    appId: project.config.appId,
    displayName: project.config.displayName,
    publisherId: project.config.publisherId,
    extensionId: project.extensionId,
    nativeHostName: project.nativeHostName,
    updateManifestUrl: project.config.update.manifestUrl
  };

  await fs.writeFile(
    path.join(project.outputDir, 'package-info.json'),
    `${JSON.stringify(packageInfo, null, 2)}\n`
  );
  await fs.writeFile(path.join(project.outputDir, 'Setup.ps1'), setupScript(packageInfo));
  await fs.writeFile(path.join(project.outputDir, 'Uninstall.ps1'), uninstallScript(packageInfo));
  await fs.writeFile(path.join(project.outputDir, 'Setup.cmd'), cmdLauncher('Setup.ps1'));
  await fs.writeFile(path.join(project.outputDir, 'Uninstall.cmd'), cmdLauncher('Uninstall.ps1'));

  console.log(`Built bootstrap installer in ${project.outputDir}`);
  console.log(`Extension ID: ${project.extensionId}`);
  console.log('Run Setup.cmd on Windows.');
}

function cmdLauncher(script) {
  return `@echo off\r\npowershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -File "%~dp0${script}"\r\nif errorlevel 1 pause\r\n`;
}

function setupScript(info) {
  return `# Generated by extension-local-packager.\n` +
`$ErrorActionPreference = 'Stop'\n` +
`$appId = ${psQuote(info.appId)}\n` +
`$displayName = ${psQuote(info.displayName)}\n` +
`$publisherId = ${psQuote(info.publisherId)}\n` +
`$extensionId = ${psQuote(info.extensionId)}\n` +
`$nativeHostName = ${psQuote(info.nativeHostName)}\n` +
`$metadataUrl = ${psQuote(info.updateManifestUrl)}\n` +
`$installRoot = Join-Path $env:LOCALAPPDATA (Join-Path $publisherId $appId)\n` +
`$extensionDir = Join-Path $installRoot 'extension'\n` +
`$tempRoot = Join-Path $env:TEMP ($appId + '-install-' + [guid]::NewGuid().ToString('N'))\n` +
`$zipPath = Join-Path $tempRoot 'dist.zip'\n` +
`$newDir = Join-Path $tempRoot 'extension'\n` +
`try {\n` +
`  New-Item -ItemType Directory -Path $tempRoot -Force | Out-Null\n` +
`  $latest = Invoke-RestMethod -Uri $metadataUrl\n` +
`  if ($latest.version -notmatch '^\\d+\\.\\d+\\.\\d+(\\.\\d+)?$') { throw 'latest.json version is invalid.' }\n` +
`  if ($latest.sha256 -notmatch '^[a-fA-F0-9]{64}$') { throw 'latest.json sha256 is invalid.' }\n` +
`  Invoke-WebRequest -Uri $latest.url -OutFile $zipPath\n` +
`  $actualHash = (Get-FileHash -Path $zipPath -Algorithm SHA256).Hash.ToLowerInvariant()\n` +
`  if ($actualHash -ne $latest.sha256.ToLowerInvariant()) { throw 'Downloaded ZIP failed SHA-256 verification.' }\n` +
`  Expand-Archive -Path $zipPath -DestinationPath $newDir -Force\n` +
`  $manifestPath = Join-Path $newDir 'manifest.json'\n` +
`  if (-not (Test-Path $manifestPath)) { throw 'dist.zip must contain manifest.json at its root.' }\n` +
`  $manifest = Get-Content -Raw -Path $manifestPath | ConvertFrom-Json\n` +
`  if ($manifest.version -ne $latest.version) { throw 'manifest.json version does not match latest.json.' }\n` +
`  New-Item -ItemType Directory -Path $installRoot -Force | Out-Null\n` +
`  if (Test-Path $extensionDir) { Remove-Item -Recurse -Force $extensionDir }\n` +
`  Move-Item -Path $newDir -Destination $extensionDir\n` +
`  $installedInfo = @{ appId=$appId; displayName=$displayName; extensionId=$extensionId; nativeHostName=$nativeHostName; metadataUrl=$metadataUrl } | ConvertTo-Json\n` +
`  Set-Content -Path (Join-Path $installRoot 'package-info.json') -Value $installedInfo -Encoding UTF8\n` +
`  Copy-Item -Path (Join-Path $PSScriptRoot 'Uninstall.ps1') -Destination (Join-Path $installRoot 'Uninstall.ps1') -Force\n` +
`  Copy-Item -Path (Join-Path $PSScriptRoot 'Uninstall.cmd') -Destination (Join-Path $installRoot 'Uninstall.cmd') -Force\n` +
`  Set-Clipboard -Value $extensionDir\n` +
`  Start-Process 'chrome.exe' 'chrome://extensions/'\n` +
`  Write-Host \"Installed $displayName\"\n` +
`  Write-Host \"Extension folder copied to clipboard: $extensionDir\"\n` +
`  Write-Host 'Enable Developer mode, choose Load unpacked, and paste the folder path.'\n` +
`} finally {\n` +
`  if (Test-Path $tempRoot) { Remove-Item -Recurse -Force $tempRoot }\n` +
`}\n`;
}

function uninstallScript(info) {
  return `# Generated by extension-local-packager.\n` +
`$ErrorActionPreference = 'Stop'\n` +
`$appId = ${psQuote(info.appId)}\n` +
`$displayName = ${psQuote(info.displayName)}\n` +
`$publisherId = ${psQuote(info.publisherId)}\n` +
`$nativeHostName = ${psQuote(info.nativeHostName)}\n` +
`$installRoot = Join-Path $env:LOCALAPPDATA (Join-Path $publisherId $appId)\n` +
`$nativeRegistry = \"HKCU:\\Software\\Google\\Chrome\\NativeMessagingHosts\\$nativeHostName\"\n` +
`if (Test-Path $nativeRegistry) { Remove-Item -Recurse -Force $nativeRegistry }\n` +
`Start-Process 'chrome.exe' 'chrome://extensions/'\n` +
`Write-Host \"Remove $displayName from Chrome on the extensions page.\"\n` +
`Write-Host \"Installed files will be removed after this window closes.\"\n` +
`$escapedRoot = $installRoot.Replace('&', '^&')\n` +
`$cleanupArgs = '/d /c ping 127.0.0.1 -n 3 >nul & rmdir /s /q "' + $escapedRoot + '"'\n` +
`Start-Process -WindowStyle Hidden -FilePath 'cmd.exe' -ArgumentList $cleanupArgs\n`;
}
